# Generated by Django 4.1.7 on 2023-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plato', models.CharField(max_length=100)),
                ('resumen', models.TextField(max_length=1000)),
                ('tiempo_en_min', models.FloatField()),
                ('porciones', models.FloatField()),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('fecha_de_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
