# Generated by Django 4.1.7 on 2023-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetario', '0002_receta_imagen_receta_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='tiempo_en_min',
            field=models.IntegerField(),
        ),
    ]
