# Generated by Django 4.1.7 on 2023-03-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetario', '0005_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(),
        ),
    ]
