# Generated by Django 4.1.7 on 2023-03-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetario', '0006_alter_receta_porciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
